spring:
  application:
    name: MotoClubeSaas

  datasource:
    url: jdbc:postgresql://localhost:5432/motoclube
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true